name: OpenSource Library Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-lib:
    uses: blimit-dev/infra-pipelines/.github/workflows/deploy-opensource-lib.yml@main
    secrets: inherit
    with:
      node-version: "24.4.1"
      branch: ${{ github.ref_name }}
