name: OpenSource Library Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write
  id-token: write  # Required for OIDC

jobs:
  deploy-npm-lib:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.4.1"
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: UPDATE APPLICATION VERSION
        run: |
          git config user.name "BLIMIT ADMIN"
          git config user.email ${{ secrets.ADMIN_EMAIL }}
          pnpm version patch
          git add package.json
          git push --follow-tags

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm publish --no-git-checks --access public
